
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//
logic [7:0] tmp;

cpu c1(
		.clk(CLK),
		.rst(~BTN[1]),
		.port_b_out(tmp)
);
Decoder_7seg d1(
	.A(tmp[7:4]),
	.res(HEX1)
);
Decoder_7seg d2(
	.A(tmp[3:0]),
	.res(HEX0)
);
// add module here




//*******************************//

endmodule
